ARG NODE_VERSION=18-alpine
FROM node:${NODE_VERSION} as runner
WORKDIR /app

COPY ./package.json package-lock.json ./
COPY ./apps/msal-react-demo/next.config.js ./
COPY ./apps/msal-react-demo/.next ./.next
COPY ./apps/msal-react-demo/public ./public

RUN npm ci

EXPOSE 3000

ARG NEXT_PUBLIC_AZURE_B2C_AUTHORITY
ARG NEXT_PUBLIC_AZURE_B2C_CLIENT_ID
ARG NEXT_PUBLIC_AZURE_B2C_FLOW_EDIT_PROFILE
ARG NEXT_PUBLIC_AZURE_B2C_FLOW_FORGOT_PASSWORD
ARG NEXT_PUBLIC_AZURE_B2C_FLOW_SIGN_UP_SIGN_IN
ARG NEXT_PUBLIC_AZURE_B2C_REDIRECT_URI
ARG NEXT_PUBLIC_AZURE_B2C_TENANT_ID

ENV NEXT_PUBLIC_AZURE_B2C_AUTHORITY=$NEXT_PUBLIC_AZURE_B2C_AUTHORITY
ENV NEXT_PUBLIC_AZURE_B2C_CLIENT_ID=$NEXT_PUBLIC_AZURE_B2C_CLIENT_ID
ENV NEXT_PUBLIC_AZURE_B2C_FLOW_EDIT_PROFILE=$NEXT_PUBLIC_AZURE_B2C_FLOW_EDIT_PROFILE
ENV NEXT_PUBLIC_AZURE_B2C_FLOW_FORGOT_PASSWORD=$NEXT_PUBLIC_AZURE_B2C_FLOW_FORGOT_PASSWORD
ENV NEXT_PUBLIC_AZURE_B2C_FLOW_SIGN_UP_SIGN_IN=$NEXT_PUBLIC_AZURE_B2C_FLOW_SIGN_UP_SIGN_IN
ENV NEXT_PUBLIC_AZURE_B2C_REDIRECT_URI=$NEXT_PUBLIC_AZURE_B2C_REDIRECT_URI
ENV NEXT_PUBLIC_AZURE_B2C_TENANT_ID=$NEXT_PUBLIC_AZURE_B2C_TENANT_ID

CMD ["npx", "next", "start", "-p", "3000"]